[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
myspltoken = "53Tt3YDUVYtWBQEyWZdHebdDFebfhjt9fMAwG6D3uAEz"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "https://solana-devnet.g.alchemy.com/v2/u8NCITxCIZ_Hj4DOZ0DEII7kSJBctO-9"
#cluster = "localnet"
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
